### ISSUE TITLE
关于版权

### ISSUE THREAD

**Issue by sy618** [zhengpu1/hosts#1]
你这个项目里与我的项目
https://github.com/sy618/hosts
hosts、dnsmasq规则等内容都是基本相同，你还把我里面的项目网址替换掉，是不是太不厚道了？

**Comment by zhengpu1** [comment]
实属好奇，自己测试而已，实在抱歉项目已删除。

**Comment by sy618** [comment]
可以转载，甚至合作维护，但必须署名。就这样。
